
export const DATABASE_CONNECTION_ERROR = {
    CONNECTION_FAILED : 'Unable to establish database Connection'
}

export const ERROR_CODES ={
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    REQUEST_DID_NOT_MATCH: "REQUEST_DID_NOT_MATCH",
    UNAUTHORIZED: "UNAUTHORIZED",
    INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT"
}